# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('sample_cover', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=2000)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputbox.Article')),
            ],
        ),
    ]
